# Generated by Django 3.1.7 on 2021-05-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal_info_Admin',
        ),
    ]
