# Generated by Django 3.1.7 on 2021-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_delete_personal_info_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_information',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Back_Upload_Aadhar',
            field=models.ImageField(null=True, upload_to='customerdocuments'),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='DOB',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Front_Upload_Aadhar',
            field=models.ImageField(null=True, upload_to='customerdocuments'),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Mother_Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Upload_Image',
            field=models.ImageField(null=True, upload_to='customerdocuments'),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Upload_Pancard',
            field=models.ImageField(null=True, upload_to='customerdocuments'),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Upload_Rent_Agreement',
            field=models.ImageField(null=True, upload_to='customerdocuments'),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='Upload_Salary_Slip',
            field=models.ImageField(null=True, upload_to='customerdocuments'),
        ),
    ]
