# Generated by Django 3.1.7 on 2021-05-13 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_auto_20210513_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_information',
            name='Back_Upload_Aadhar',
        ),
        migrations.RemoveField(
            model_name='personal_information',
            name='Front_Upload_Aadhar',
        ),
        migrations.RemoveField(
            model_name='personal_information',
            name='Upload_Image',
        ),
        migrations.RemoveField(
            model_name='personal_information',
            name='Upload_Pancard',
        ),
        migrations.RemoveField(
            model_name='personal_information',
            name='Upload_Rent_Agreement',
        ),
        migrations.RemoveField(
            model_name='personal_information',
            name='Upload_Salary_Slip',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Front_Upload_Aadhar', models.ImageField(null=True, upload_to='customerdocuments')),
                ('Back_Upload_Aadhar', models.ImageField(null=True, upload_to='customerdocuments')),
                ('Upload_Pancard', models.ImageField(null=True, upload_to='customerdocuments')),
                ('Upload_Image', models.ImageField(null=True, upload_to='customerdocuments')),
                ('Upload_Salary_Slip', models.ImageField(null=True, upload_to='customerdocuments')),
                ('Upload_Rent_Agreement', models.ImageField(null=True, upload_to='customerdocuments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
