# Generated by Django 3.1.7 on 2021-05-14 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0004_auto_20210514_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Upload_Image',
            field=models.ImageField(blank=True, null=True, upload_to='customerdocuments'),
        ),
        migrations.AlterField(
            model_name='document',
            name='Upload_Pancard',
            field=models.ImageField(blank=True, null=True, upload_to='customerdocuments'),
        ),
        migrations.AlterField(
            model_name='document',
            name='Upload_Rent_Agreement',
            field=models.ImageField(blank=True, null=True, upload_to='customerdocuments'),
        ),
        migrations.AlterField(
            model_name='document',
            name='Upload_Salary_Slip',
            field=models.ImageField(blank=True, null=True, upload_to='customerdocuments'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
