# Generated by Django 3.1.7 on 2021-05-14 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0005_auto_20210514_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
                ('Amount_Need', models.IntegerField()),
                ('Tenure', models.CharField(choices=[('3 month', '3 month'), ('6 month', '6 month'), ('9 month', '9 month'), ('12 month', '12 month')], max_length=20)),
                ('Interest', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
