# Generated by Django 3.1.7 on 2021-05-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_apply_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_loan',
            name='Interest',
        ),
        migrations.AddField(
            model_name='apply_loan',
            name='Rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
