# Generated by Django 3.1.7 on 2021-05-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210515_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Upload_Rent_Agreement',
            new_name='Upload_Income_Proof',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='Upload_Salary_Slip',
            new_name='Upload_Residence_Proof',
        ),
    ]
