# Generated by Django 3.1.7 on 2021-05-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210515_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_loan',
            name='Loan_Status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=30, null=True),
        ),
    ]
