# Generated by Django 3.1.7 on 2021-05-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminss', '0002_auto_20210510_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='category',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('Customer', 'Customer')], max_length=15, null=True),
        ),
    ]
