# Generated by Django 3.1.7 on 2021-05-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminss', '0004_personal_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal_Information',
        ),
    ]
